FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html
COPY status /usr/share/nginx/html/status
COPY threats /usr/share/nginx/html/threats
COPY status.json /usr/share/nginx/html/status.json
